### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BarehSolok** [dcsoft-yyf/JIEJIE.NET#3]
I got this error after it attempt to saving assembly
> error : syntax error at token 'IL_00d1' in:             IL_00d1:    call      class [mscorlib]System.Reflection.MethodBase [mscorlib]System.Reflection.MethodBase::GetMethodFromHandle(valuetype [mscorlib]System.RuntimeMethodHandle)

**Comment by dcsoft-yyf** [comment]
hi. please send your assembly binary file to me.



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 4, 2021 17:14 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [dcsoft-yyf/JIEJIE.NET] Error (#3)




 
I got this error after it attempt to saving assembly
  
error : syntax error at token 'IL_00d1' in:             IL_00d1:    call      class [mscorlib]System.Reflection.MethodBase [mscorlib]System.Reflection.MethodBase::GetMethodFromHandle(valuetype [mscorlib]System.RuntimeMethodHandle)
  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
